defaultSemverRangePrefix: ""

enableGlobalCache: false
nodeLinker: pnp
pnpMode: strict
pnpFallbackMode: none

supportedArchitectures:
  os:
    - current
    - linux
  libc:
    - current
    - glibc

packageExtensions:
  mocha@9.2.2:
    dependencies:
      ts-node: 10.9.2